### ISSUE TITLE
System Preferences Open Before User Interacts With Prompt

### ISSUE THREAD

**Issue by MaddHatters** [codebytere/node-mac-permissions#13]
When calling `askForAccessibilityAccess()`, the system preferences window is opened shortly after the prompt is displayed but before the user has interacted with the prompt.

**node-mac-permissions version:** 1.4.1

**macOS versions:**
Catalina 10.15.4, 10.15.5

```
   const { askForAccessibilityAccess} = require('node-mac-permissions');
   askForAccessibilityAccess();
```

**Comment by codebytere** [comment]
@MaddHatters i'll try to dig into this but this is a bit of a function of the way that macOS itself handles the native function underlying the function. Latest stable version handles this by turning off the prompt and just opening sysprefs by default.

**Comment by MaddHatters** [comment]
@codebytere Thank you for replying so quickly and for the explanation. 

I've updated to the latest stable version (2.1.3) and it's working great. I can just create a custom prompt and use askForAccessibilityAccess() to open system preferences after a response from the user.

Thank you :)

**Comment by codebytere** [comment]
@MaddHatters glad to hear :D i'm gonna close this out but feel free to lmk if anything else comes up!
