### ISSUE TITLE
Fix IT NOW    (Home-Effiency-Cost-Savings-Calculator)

### ISSUE THREAD

**Issue by david12481** [codebytere/node-mac-permissions#22]
For creation of annual tune-ups for Heating&Cooling/Refrigeration systems and replacement for higher seer ratings and btu's.        Customer Log-Ins For Easier Data Base Home Or Buisness Measurements R-Values And Age of Property For Easy Access And Customer Friendly Insights For Annual Service And Fuel/Power Savings

Customer Interaction App Download Located On OUR Buisness Site And Appstore With Our Buisness Credentials

For Further Sales And Tune-ups & Customer And Brand Analytics￼

**Comment by alectrocute** [comment]
Spam, reporting user.
