### ISSUE TITLE
Add support for keyboard / mouse capture permissions (CGEventTapCreate)

### ISSUE THREAD

**Issue by miniak** [codebytere/node-mac-permissions#33]
https://asciiwwdc.com/2019/sessions/701
> Monitoring all keyboard events, including those for other apps, however, requires user approval.
>
> And here you can see an example of using CGEventTapCreate to invoke a callback for key press and release events.
>
> Now, the first time this code runs, this call, the CGEventTapCreate will fail and return nil.
>
> Meanwhile, a dialog is displayed directing the user to the security and privacy preference pane, where the user can approve your app to monitor keyboard events in the background, if they so desire.
>
> Now, apps may check the authorization status without triggering the approval prompt, using the IOHIDCheckAccess function with the kIOHIDRequestTypeListenEvent parameter.
>
> And apps can request an approval dialog to be displayed without creating an event tab or trying to post an event by using the IOHIDRequestAccess function, again with the same parameter.
>
> So in summary, macOS Catalina now requires user consent for apps to record the contents of your screen or the keys that you type on your keyboard.

**Comment by codebytere** [comment]
ty @miniak i'll do this soon!
