### ISSUE TITLE
Commit for adding missing function in TS doesn't seem to be present in v2.2.0

### ISSUE THREAD

**Issue by meghnagoelgithub** [codebytere/node-mac-permissions#34]
Hi, I have the latest master that corresponds to v2.2.0. I do not see the following commit:

<img width="1224" alt="Screenshot 2021-12-23 at 6 58 07 AM" src="https://user-images.githubusercontent.com/96555789/147174262-3e78e439-2963-4b69-8f9c-af0e51e748dc.png">

present in the index.d.ts that I got with v2.2.0. Could you please check.

**Comment by cereme** [comment]
This should be fixed for typescript users.

**Comment by codebytere** [comment]
Closed in https://github.com/codebytere/node-mac-permissions/releases/tag/v2.3.0
