### ISSUE TITLE
npm registry version is off

### ISSUE THREAD

**Issue by glawson** [codebytere/node-mac-permissions#4]
https://www.npmjs.com/package/node-mac-permissions still shows current version as 1.4.0, latest is 1.5.0.

https://docs.npmjs.com/updating-your-published-package-version-number

**Comment by codebytere** [comment]
Hi yes - i haven't had a change to draft a new release or run publish yet. I will as soon as i can!

**Comment by glawson** [comment]
💯- thanks.  Please let me know if I can help.

**Comment by codebytere** [comment]
Since it's breaking, per semver i also need to bump it to `2.0.0` - as soon as that's done i'll publish :)

**Comment by codebytere** [comment]
Done: https://www.npmjs.com/package/node-mac-permissions/v/2.0.0

Thanks for the reminder!
