### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by vraravam** [codebytere/node-mac-permissions#42]
Thanks for this cool library! I see that the last release was back in 2020, and since then, there have been some very important changes. The one I am interested in is the one that specifies the `os` in the module spec. Could you please release a new version so that consumers are not pulling from GH?

**Comment by codebytere** [comment]
Sure! I'll try to get one out by the end of my day today.

**Comment by codebytere** [comment]
@vraravam done: https://github.com/codebytere/node-mac-permissions/releases/tag/v2.3.0

**Comment by vraravam** [comment]
thank you @codebytere !
