### ISSUE TITLE
Package cannot be used with electron-builder 23.2.0 on Monterey

### ISSUE THREAD

**Issue by has-n** [codebytere/node-mac-permissions#45]
If you're building on Monterey, you first run into #39 .

You install Python but versions of electron-builder prior to 23 use the baked in Python which fails. 

You then upgrade electron-builder to 23.2.0 but now run into https://github.com/electron/universal/issues/41 

You wonder at life's purpose.

**Comment by JamesS-M** [comment]
I'm having this issue as well.

**Comment by codebytere** [comment]
`electron-builder` is neither maintained nor recommended by the Electron core team - i'm happy to try to take a look though.

in the meantime: https://github.com/electron/universal/issues/41#issuecomment-1181311686 looks like it might help?

**Comment by JamesS-M** [comment]
> in the meantime: [electron/universal#41 (comment)](https://github.com/electron/universal/issues/41#issuecomment-1181311686) looks like it might help?

That works 😄

**Comment by codebytere** [comment]
Closing as there's a workaround and the root problem is best solved in builder.
