### ISSUE TITLE
askForInputMonitoringAccess is not included on npm install

### ISSUE THREAD

**Issue by mister-10k** [codebytere/node-mac-permissions#51]
I recently downloaded this of input monitoring, but it is not available in the current release in npm

**Comment by RewriteH** [comment]
+1

**Comment by levpopov** [comment]
+1 would be nice to have this packaged in a release.

For anyone looking for a temp workaround - just install the package from a local source tree.

**Comment by codebytere** [comment]
https://www.npmjs.com/package/node-mac-permissions/v/2.3.0
