### ISSUE TITLE
Full Disk Access always return unauthorised on MacOS Ventura

### ISSUE THREAD

**Issue by vddgil** [codebytere/node-mac-permissions#56]
Full Disk Access always returns unauthorised on MacOS Ventura

It's happening in development and in the production build.
The app was working perfectly with Monterey.

Does anyone have the same issue?

**Comment by superkraft-io** [comment]
I have the same problem.

I add the app to the FDA list, MacOS asks me to quit the app, I click to quit it, but the app doesn't even terminate.

Even if I manually force quit the app, seems like FDA is not permitted no matter how I try it.

**Comment by aidv** [comment]
I have the same problem.

I add the app to the FDA list, MacOS asks me to quit the app, I click to quit it, but the app doesn't even terminate.

Even if I manually force quit the app, seems like FDA is not permitted no matter how I try it.

**Comment by codebytere** [comment]
https://github.com/codebytere/node-mac-permissions/commit/c1bf50e22858162141af7242b565472d6038fe55 should address it.

**Comment by aidv** [comment]
> [c1bf50e](https://github.com/codebytere/node-mac-permissions/commit/c1bf50e22858162141af7242b565472d6038fe55) should address it.

But it's not.

Closing this issue is just taking the easy way out.

**Comment by codebytere** [comment]
@aidv what are you talking about?

**Comment by aidv** [comment]
> @aidv what are you talking about? This module does not add apps to FDA.
> 
> I am running macOS Ventura, and when iTerm has been given full disk access:
> 
> <img alt="Screenshot 2023-02-14 at 12 17 47 PM" width="502" src="https://user-images.githubusercontent.com/2036040/218721774-86ac09e0-8e89-4891-b3f9-4b8cbeaada7d.png">
> 
> And i run
> 
> ```js
> const { getAuthStatus } = require('node-mac-permissions')
> console.log(getAuthStatus('full-disk-access'))
> ```
> 
> I correctly see `authorized` in my console. The version which contains the above commit is v2.3.0, which i just released this morning.

Your Console, yes, it works for me too when I give access to my console.

But a console is not what's deployed in production.

In production, when real users use the app, they'd add the app.
