### ISSUE TITLE
[BUG] Requesting accessibility permission in Electron program is always denied.

### ISSUE THREAD

**Issue by mushan0x0** [codebytere/node-mac-permissions#59]
electron: 22.0.3
node-mac-permissions: 2.3.0

Calling `permissions.getAuthStatus("accessibility")` in development version is fine, but after installing the packaged Electron program for the second time, calling `permissions.getAuthStatus("accessibility")` will always return `denied`, even if resetting the permission or reinstalling it does not work 😢.

**Comment by suan** [comment]
Can we get a new release that includes this fix? Thanks!

**Comment by suan** [comment]
Or @mushan0x0 what ended up being the problem, if a fix wasn’t required? Running into the same issue here.

**Comment by mushan0x0** [comment]
> Or @mushan0x0 what ended up being the problem, if a fix wasn’t required? Running into the same issue here.

@suan It seems to be related to the .plist file of Mac, I'm not sure though. Here is my configuration, you can take a look:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
  </dict>
</plist>
```
