### ISSUE TITLE
Fails to build on macOS 10.13 Xcode 10.0

### ISSUE THREAD

**Issue by glawson** [codebytere/node-mac-permissions#6]
Hi @codebytere,

Ran into an issue building on Travis.  We're using the osx_image [xcode10](https://docs.travis-ci.com/user/reference/osx/#macos-version) and getting the following errors (below).  I'm a bit baffled as I thought `@available(macOS 10.14, *)` would take care of that (??).  We have to keep the backwards compatibility - is there any precompiler flags we're missing?

Thanks 

[5/5] Building fresh packages...
error /Users/travis/build/loomhq/desktop/node_modules/node-mac-permissions: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/travis/build/loomhq/desktop/node_modules/node-mac-permissions
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.16.1 | darwin | x64
gyp info find Python using Python version 2.7.17 found at "/usr/local/opt/python@2/bin/python2.7"
gyp http GET https://nodejs.org/download/release/v12.16.1/node-v12.16.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.16.1/node-v12.16.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.16.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.16.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/Users/travis/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/travis/build/loomhq/desktop/node_modules/node-mac-permissions/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/travis/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/travis/Library/Caches/node-gyp/12.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/travis/Library/Caches/node-gyp/12.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/travis/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/travis/Library/Caches/node-gyp/12.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/travis/build/loomhq/desktop/node_modules/node-mac-permissions',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/permissions/permissions.o
../permissions.mm:158:5: error: 'AVAuthorizationStatus' is unavailable: not available on macOS
    AVAuthorizationStatus status =
    ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1456:28: note: 'AVAuthorizationStatus' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVAuthorizationStatus) {
                           ^
../permissions.mm:159:26: error: 'authorizationStatusForMediaType:' is unavailable: not available on macOS
        [AVCaptureDevice authorizationStatusForMediaType:media_type];
                         ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1479:1: note: 'authorizationStatusForMediaType:' has been explicitly marked unavailable here
+ (AVAuthorizationStatus)authorizationStatusForMediaType:(AVMediaType)mediaType NS_AVAILABLE_IOS(7_0);
^
../permissions.mm:161:19: error: 'AVAuthorizationStatusAuthorized' is unavailable: not available on macOS
    if (status == AVAuthorizationStatusAuthorized)
                  ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1456:28: note: 'AVAuthorizationStatus' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVAuthorizationStatus) {
                           ^
../permissions.mm:163:24: error: 'AVAuthorizationStatusDenied' is unavailable: not available on macOS
    else if (status == AVAuthorizationStatusDenied)
                       ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1456:28: note: 'AVAuthorizationStatus' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVAuthorizationStatus) {
                           ^
../permissions.mm:165:24: error: 'AVAuthorizationStatusRestricted' is unavailable: not available on macOS
    else if (status == AVAuthorizationStatusRestricted)
                       ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1456:28: note: 'AVAuthorizationStatus' has been explicitly marked unavailable here
typedef NS_ENUM(NSInteger, AVAuthorizationStatus) {
                           ^
../permissions.mm:312:11: error: 'requestAccessForMediaType:completionHandler:' is unavailable: not available on macOS
          requestAccessForMediaType:AVMediaTypeVideo
          ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1502:1: note: 'requestAccessForMediaType:completionHandler:' has been explicitly marked unavailable here
+ (void)requestAccessForMediaType:(AVMediaType)mediaType completionHandler:(void (^)(BOOL granted))handler NS_AVAILABLE_IOS(7_0);
^
../permissions.mm:352:11: error: 'requestAccessForMediaType:completionHandler:' is unavailable: not available on macOS
          requestAccessForMediaType:AVMediaTypeAudio
          ^
/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:1502:1: note: 'requestAccessForMediaType:completionHandler:' has been explicitly marked unavailable here
+ (void)requestAccessForMediaType:(AVMediaType)mediaType completionHandler:(void (^)(BOOL granted))handler NS_AVAILABLE_IOS(7_0);
^
7 errors generated.
make: *** [Release/obj.target/permissions/permissions.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/travis/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/travis/.nvm/versions/node/v12.16.1/bin/node" "/Users/travis/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/travis/build/loomhq/desktop/node_modules/node-mac-permissions
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by codebytere** [comment]
@glawson you're right - that needs a 10.14 guard (see [doc](https://developer.apple.com/documentation/avfoundation/avauthorizationstatus/avauthorizationstatusauthorized?language=objc)). I'll get a PR up asap!

**Comment by glawson** [comment]
@codebytere - just to make sure I'm clear, you are referencing using a newer swift sdk?  We're using swift 4, I'll try swift 4.2 and let you know.

**Comment by codebytere** [comment]
@glawson this is an Objective-C module only (no swift involved) - i'm referring to the macOS SDK.

**Comment by glawson** [comment]
@codebytere what is the min SDK I'd need to get the enums?

**Comment by glawson** [comment]
@codebytere - I'm going to close this.  I was able to upgrade to the Travis xcode10.3 image - which fixed the build issues.  Thank you for your help.

**Comment by codebytere** [comment]
Awesome, glad it worked! Feel free to ping if there are any more issues 🙇‍♀️
