### ISSUE TITLE
Calendar & Reminder Access changes in Sonoma

### ISSUE THREAD

**Issue by theDevelopper** [codebytere/node-mac-permissions#73]
Apple has changed how to request access to calendars and reminders with macOS 14 (Sonoma). This package uses the now deprecated `requestAccessToEntityType:completion:` method.

> Deprecated
> On [macOS 14] and later, this method doesn’t prompt for access and immediately calls the completion block with an error.
> If your app only uses [EKEventEditViewController](https://developer.apple.com/documentation/eventkitui/ekeventeditviewcontroller?language=objc) to let your user create and save calendar events, don’t request events access. Use [requestWriteOnlyAccessToEventsWithCompletion:](https://developer.apple.com/documentation/eventkit/ekeventstore/4162274-requestwriteonlyaccesstoeventswi?language=objc) to create calendar events. Use [requestFullAccessToEventsWithCompletion:](https://developer.apple.com/documentation/eventkit/ekeventstore/4162272-requestfullaccesstoeventswithcom?language=objc) to read and write calendar events. Use [requestFullAccessToRemindersWithCompletion:](https://developer.apple.com/documentation/eventkit/ekeventstore/4162273-requestfullaccesstoreminderswith?language=objc) to read and write reminders.

See: https://developer.apple.com/documentation/eventkit/ekeventstore/1507547-requestaccesstoentitytype?language=objc

To mitigate this in the meantime, one has to define the following Properties in the `info.plist`:

- [NSCalendarsWriteOnlyAccessUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscalendarswriteonlyaccessusagedescription)
- [NSCalendarsFullAccessUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscalendarsfullaccessusagedescription)
- [NSRemindersFullAccessUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersfullaccessusagedescription?language=objc)

In the long run, this package should not use the deprecated method but the new ones instead.

**Comment by codebytere** [comment]
Closed in fd7129c
