### ISSUE TITLE
Release of v2.4.0 on NPM

### ISSUE THREAD

**Issue by raphaelmenges** [codebytere/node-mac-permissions#74]
Hello 👋,

thank you for this module, I use it successfully to manage permissions on macOS. Thus, I observed that you have released a [new version 2.4.0](https://github.com/codebytere/node-mac-permissions/releases/tag/v2.4.0) recently on GitHub, which is [not yet available on NPM](https://www.npmjs.com/package/node-mac-permissions?activeTab=versions). I managed to add the dependency from your GitHub repository instead of NPM, but I would be glad to acquire your module from NPM again. Could you upgrade the version available on NPM?

Cheers,
Raphael

**Comment by codebytere** [comment]
@raphaelmenges oops, my bad! done :D 

https://www.npmjs.com/package/node-mac-permissions/v/2.4.0
