### ISSUE TITLE
Add TS types for module.

### ISSUE THREAD

**Issue by codebytere** [codebytere/node-mac-permissions#9]
Add TypeScript type definitions for various functions.

**Comment by glawson** [comment]
@codebytere - I'll take this one on.

**Comment by codebytere** [comment]
@glawson rad, thanks!

**Comment by codebytere** [comment]
@glawson are you still interested in this? i might open it up to a wider audience for potential contributions if no :)

**Comment by glawson** [comment]
@codebytere - yes, I'll get it done by EOD tomorrow.

**Comment by codebytere** [comment]
Closed in https://github.com/codebytere/node-mac-permissions/pull/15
